"""
Builds the complete BCSP-064 project report as a Word document.

The document is built in two passes. The first pass runs the body purely to
collect the figure and table captions; the second emits the final document with
the List of Figures and List of Tables in the front matter, where they belong,
rather than at the end. The build is deterministic, so the numbering produced by
the two passes is identical.

Run:  python3 build_report.py
"""
import os
import sys
import pathlib

BASE = pathlib.Path(__file__).parent
sys.path.insert(0, str(BASE))

from docx_kit import Report, ACCENT          # noqa: E402
import content_front                          # noqa: E402
import content_synopsis                       # noqa: E402
import content_resources                      # noqa: E402
import content_ch1_3                          # noqa: E402
import content_ch4_5                          # noqa: E402
import content_ch6_7                          # noqa: E402
import content_ch8                            # noqa: E402
import content_ch9_13                         # noqa: E402
import content_appendix                       # noqa: E402

BODY = (content_ch1_3, content_ch4_5, content_ch6_7, content_ch8, content_ch9_13)


def build_body(r, ref_index=None):
    r.ref_index = ref_index or {}
    for module in BODY:
        module.build(r)


def main():
    # ---- Pass 1: collect the body's figure and table captions -------------
    # This also builds the index that resolves every symbolic cross-reference
    # ("see Table N") in the second pass.
    probe = Report()
    build_body(probe)
    figures = list(probe.figures)
    tables = list(probe.tables)
    ref_index = probe.make_ref_index()

    # ---- Pass 2: emit the final document --------------------------------
    r = Report()
    r.add_page_numbers()
    r.add_header_text('BCA Project (BCSP-064) — Kailash Kumar Jha — 2400767095')

    r.ref_index = ref_index
    content_front.build(r)
    content_resources.build(r)      # QR codes, omitted when no URL is set
    content_synopsis.build(r)

    r.page_break()
    r.centered('TABLE OF CONTENTS', 16, bold=True, colour=ACCENT, space_after=6)
    r.rule()
    r.spacer(8)
    r.p('This contents page is generated by Word from the document headings. To populate or '
        'refresh it, open the document in Microsoft Word, click anywhere in the table below '
        'and press F9 (on macOS, Command-Option-Shift-U), then choose "Update entire table". '
        'In LibreOffice Writer, use Tools → Update → Indexes and Tables.',
        first_line_indent=False, italic=True, size=10.5, spacing='single')
    r.spacer(8)
    r.toc_field('1-3')

    r.page_break()
    r.centered('LIST OF FIGURES', 15, bold=True, colour=ACCENT, space_after=6)
    r.rule()
    r.spacer(8)
    r.table(['Figure', 'Caption'], [[a, b] for a, b in figures],
            widths=[0.65, 3.65], font_size=8.5)

    r.page_break()
    r.centered('LIST OF TABLES', 15, bold=True, colour=ACCENT, space_after=6)
    r.rule()
    r.spacer(8)
    r.table(['Table', 'Caption'], [[a, b] for a, b in tables],
            widths=[0.65, 3.65], font_size=8.5)

    # The two index tables above are themselves uncaptioned and so consume no
    # number; the counters are reset here only because the front matter and the
    # synopsis run before them.
    r.figure_no = 0
    r.table_no = 0
    r.figures.clear()
    r.tables.clear()

    build_body(r, ref_index)
    total_lines = content_appendix.build(r)

    assert [f[0] for f in r.figures] == [f[0] for f in figures], \
        'figure numbering diverged between passes'
    assert [t[0] for t in r.tables][:len(tables)] == [t[0] for t in tables], \
        'table numbering diverged between passes'

    public = os.environ.get('IGNOU_REDACT') == '1'
    out = BASE / ('BCA_Project_Report_BCSP064_Kailash_Kumar_Jha'
                  + ('_PUBLIC' if public else '') + '.docx')
    r.save(out)

    print(f'  figures : {len(figures)}')
    print(f'  tables  : {len(tables)}')
    print(f'  code    : {total_lines:,} lines reproduced in Appendix A')
    print(f'  saved   : {out.name}')
    print(f'  size    : {out.stat().st_size / 1024 / 1024:.1f} MB')


if __name__ == '__main__':
    main()
